# pybind11 类型桩 — quoridor_cpp 模块
# 仅供 Pylance 类型检查，运行时实际加载的是同名 .pyd

class Action:
    pos: tuple[int, int]
    is_wall: bool
    wall_dir: int
    def __init__(self, pos: tuple[int, int], is_wall: bool, wall_dir: int) -> None: ...
    def apply(self, state: "State") -> bool: ...

class State:
    turn: int
    def reset(self) -> None: ...
    def get_pos(self, player: int) -> tuple[int, int]: ...
    def set_pos(self, player: int, row: int, col: int) -> None: ...
    def get_wall_num(self, player: int) -> int: ...
    def set_wall_num(self, player: int, n: int) -> None: ...
    def get_cell(self, r: int, c: int) -> bool: ...
    def set_cell(self, r: int, c: int, v: bool) -> None: ...
    def get_h_wall(self, r: int, c: int) -> bool: ...
    def get_v_wall(self, r: int, c: int) -> bool: ...
    def copy(self) -> "State": ...

def isconnect(state: State, start: tuple[int, int], target_row: int) -> bool: ...
def get_legal_moves(state: State, player: int) -> list[tuple[int, int]]: ...
def get_legal_walls(state: State, player: int) -> list[tuple[int, int, int]]: ...
def get_legal_actions(state: State) -> list[Action]: ...

ROW_SIZE: int = 9
COLUMN_SIZE: int = 9
WALL_NUM: int = 10
WALL_LENGTH: int = 2
ACTION_NUM: int = 225
ROW_MAX: int = 18
COL_MAX: int = 18
BOARD_SIZE: int = 19
